spring:
  application:
    name: token-service

  datasource:
    url: jdbc:postgresql://localhost:5433/tokendb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8082

# API Key for authentication
api:
  key: your-secret-api-key-change-in-production

# Encryption secret key (256-bit)
encryption:
  secret:
    key: MySecretKey1234567890123456789012

# Token rejection probability (0.0 to 1.0) - default is 30%
token:
  rejectionProbability: 0.3

# Payment configuration
payment:
  rejectionProbability: 0.3
  retryCount: 3

# Email configuration (mock for now)
email:
  enabled: false
  from: noreply@farmatodo.com

# Logging configuration
logging:
  level:
    com.farmatodo.token_service: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{transactionId}] %-5level %logger{36} - %msg%n"
