spring:
  application:
    name: client-service

  datasource:
    url: jdbc:postgresql://localhost:5432/clientdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8081

# API Key for authentication
api:
  key: client-service-api-key-change-in-production

# Product search configuration
product:
  minStock: 0  # Only return products with stock greater than this value

# Logging configuration
logging:
  level:
    com.farmatodo.client_service: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{transactionId}] %-5level %logger{36} - %msg%n"
