# Order Service - Default Configuration (applies to all profiles)
spring:
  application:
    name: order-service

server:
  port: 8085

# API Key for authentication
api:
  key: order-service-api-key-change-in-production

# Payment configuration
payment:
  rejectionProbability: 0.3
  retryCount: 3

# Email configuration
email:
  enabled: false
  from: noreply@farmatodo.com

# Logging configuration
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{transactionId}] %-5level %logger{36} - %msg%n"
